### ISSUE TITLE
Error reading concept in Tesla Q10 2023 July 24th

### ISSUE THREAD

**Issue by gmconte** [ammasjk/xbrlj#3]
Hi, I just found a bug with this document:
https://www.sec.gov/Archives/edgar/data/1318605/000095017023033872/0000950170-23-033872-xbrl.zip

The system finds all kind of HREF and the `keyConceptMap` contains ~20k of them.

But if you put a breakpoint with the condition `concept == null` in `DiscoverableTaxonomySet:462` you will see which href makes it fail.
Maybe it could be enough to just ignore with a try-catch and log the href causing the error, not sure.

**Comment by ammasjk** [comment]
Thanks for raising this issue. The core issue seems to be that the XBRL
imports the ecd sub taxonomy but does not include the ecd taxonomy that it
depends on. This seems to be a new taxonomy for 2023. I have committed a
fix to forcefully import the ecd taxonomy when the ecd sub taxonomy is
imported. The logic already has defensive measures in place to not revisit
a taxonomy multiple times. Treat this as a short-term fix but it does
resolve the issue you are running into. Using a try-catch to handle the
case when the concept is null is ok but it will make the XBRL incomplete.

**Comment by gmconte** [comment]
Thanks for fixing it so quickly. it works well now!
